### PR TITLE
Support configuring span events

### LINKED ISSUE #10: Support logging tracing span enter/exit
I would find it useful to get a msg when we enter/exit a span. Would you accept a PR that logs this info when under the feature `trace`?

### PR DESCRIPTION
**Pull request by danielzfranklin**
Here's a first draft of what we discussed. If this looks OK to you I'll document it.

Closes #10

### CODE REVIEW

**Comment by d-e-s-o** [comment]
The span events logic looks good to me, thanks! I don't see a reason for allowing `NONE` or empty string, though. Why do you think we need them?

Not sure about the pretty stuff, though. Have to think about it some more. I am not sure the dependencies should be added or even do what you think they do. See db6e7001cf260b8c7115c11a19ce0834cd62806d.

**Comment by d-e-s-o** [comment]
Also, can we work with lower case values by default, please? Just because they are constants in `tracing_subscriber` does not mean we have to expose uppercased strings, in my opinion. I understand you are already uppercasing (and so are pretty case independent), I am just asking for the default in code and in messages to be lower case -- similar to log levels in `env_logger`.

**Comment by d-e-s-o** [comment]
One last thing: do you really think that using a pipe as the separator makes sense? I'd find a comma to be more intuitive, coming from `env_logger`. I actually believe that `env_logger` or at least the tracing version of it already understands comma separated values (e.g., `RUST_LOG=hyper::proto=debug,hyper::proto::h1::io=trace`), so I think that would be the more natural variant here as well.

**Comment by danielzfranklin** [comment]
> The span events logic looks good to me, thanks! I don't see a reason for allowing NONE or empty string, though. Why do you think we need them?

No good reason. Removed.

>  I am not sure the dependencies should be added or even do what you think they do. See db6e700.
You're right. Fixed.

> Also, can we work with lower case values by default, please? Just because they are constants in `tracing_subscriber` does not mean we have to expose uppercased strings, in my opinion. I understand you are already uppercasing (and so are pretty case independent), I am just asking for the default in code and in messages to be lower case -- similar to log levels in `env_logger`.

Done. I also replaced `|` with `,` to be more like `env_logger`.

**Comment by d-e-s-o** [comment]
Looks awesome! Will you mention the new capabilities in the documentation somewhere as you proposed initially?

**Comment by danielzfranklin** [comment]
> Looks awesome! Will you mention the new capabilities in the documentation somewhere as you proposed initially?

How do the docs look?

**Comment by d-e-s-o** [comment]
> > Looks awesome! Will you mention the new capabilities in the documentation somewhere as you proposed initially?
> 
> How do the docs look?

Great, I'll merge it tomorrow. Thanks!

**Comment by danielzfranklin** [comment]
Should I also bump the version and make a changelog entry?

**Comment by d-e-s-o** [comment]
> Should I also bump the version and make a changelog entry?

No worries, I can take care of that.

**Comment by d-e-s-o** [comment]
I merged the tracing span change with one small bug fix: we were panicking when the new variable was empty (likely introduced because I asked to remove the `""` case). I hope I didn't introduce any new bugs.

I think I'll pass on the `trace-pretty` commit, though. While the trace events functionality is an actual value-add from my perspective, here we get too much into personal preference. There are sheer amounts of permutations possible on how to configure the output, and I don't intend to even try to capture them. The functionality provided by the crate is mostly meant as a quick way to understand issues in tests, without having to do much -- in my opinion the format should not matter very much in that case; and if I were to guess it's probably fairly similar to how most people would see the output in production.

In any case, thanks again for your contribution! Do you have other functionality you are considering adding? Otherwise I'll cut a new release.

**Comment by danielzfranklin** [comment]
Sounds good!

> here we get too much into personal preference.

Fair enough. I happen to personally prefer the opposite, but I can keep using my fork.

I'm not planning on any other changes.

**Comment by d-e-s-o** [comment]
:+1: 

FYI, I've released 0.2.6 with the changes.

**Pull request closed without merging**
